# Generated by Django 6.0 on 2026-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_id',
            field=models.CharField(blank=True, help_text='Transaction or payment gateway ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bkash_app_key',
            field=models.CharField(blank=True, help_text='bKash App Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bkash_app_secret',
            field=models.CharField(blank=True, help_text='bKash App Secret', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bkash_base_url',
            field=models.URLField(default='https://checkout.sandbox.bhash.com/v1.2.0-beta', help_text='bKash API URL', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bkash_password',
            field=models.CharField(blank=True, help_text='bKash Password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bkash_username',
            field=models.CharField(blank=True, help_text='bKash Username', max_length=255, null=True),
        ),
    ]
