# Generated by Django 6.0 on 2026-06-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_is_paid_order_payment_gateway_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='bkash_base_url',
            field=models.URLField(default='https://tokenized.sandbox.bka.sh/v1.2.0-beta', help_text='bKash API URL', max_length=500),
        ),
    ]
