# Generated by Django 6.0 on 2026-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_sitesettings_bkash_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_id',
            field=models.CharField(blank=True, help_text='Google Tag ID (gtag.js) e.g. G-XXXXXX', max_length=50, null=True),
        ),
    ]
