# Generated by Django 6.0 on 2026-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sitesettings_google_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel',
            name='layout_type',
            field=models.CharField(choices=[('classic', 'Classic Layout'), ('modern', 'Modern Layout'), ('combo', 'Combo Layout'), ('bangla', 'Bangla Funnel Layout'), ('ezymart', 'EzyMart Layout'), ('ezymart_v2', 'EzyMart V2 Layout'), ('dark', 'Dark High-Contrast Layout'), ('professional', 'Professional Two-Column Layout'), ('garden', 'Garden Green Layout'), ('premium', 'Premium Orange Layout')], default='classic', help_text='Select the visual template for this funnel', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bkash_base_url',
            field=models.URLField(help_text='bKash API URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Spaceghor', max_length=200),
        ),
    ]
