# Generated by Django 6.0.6 on 2026-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_funnel_layout_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, help_text='YouTube or external video embed URL', max_length=500, null=True),
        ),
    ]
