# Generated by Django 6.0 on 2026-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('customer', 'Customer'), ('ads_manager', 'Ads Manager')], default='customer', max_length=20),
        ),
    ]
